sudo: false
dist: trusty
language: php

notifications:
  email: false

php:
  - 7.2
  - 7.1
  - 7.0

install:
  - composer install --prefer-dist
  - |
    if [ $TRAVIS_PHP_VERSION = "7.2" ]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar \
      && chmod +x coveralls.phar
      mkdir -p build/logs
    fi

script:
  - |
    if [ $TRAVIS_PHP_VERSION = "7.2" ]; then
      ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    else
      ./vendor/bin/phpunit
    fi

after_success:
  - |
    if [ $TRAVIS_PHP_VERSION = "7.2" ]; then
      travis_retry php coveralls.phar
    fi