language: php

notifications:
  on_success: change
  on_failure: change

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.0
      dist: xenial
    - name: Code Coverage
      php: 7.3
      env: $RUN_CODE_COVERAGE=1
  allow_failures:
    - name: Code Coverage


before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install --prefer-dist --no-interaction
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar \
      && chmod +x php-coveralls.phar
      mkdir -p build/logs
    fi

script:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      phpdbg -qrr -d memory_limit=-1 ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
    else
      ./vendor/bin/phpunit
    fi

after_success:
  - |
    if [[ ${RUN_CODE_COVERAGE} ]]; then
      travis_retry php php-coveralls.phar
    fi
